const dotenv = require("dotenv");
dotenv.config();
const userRoutes = require("./routes/user.routes");
const express = require("express");
const cors = require("cors");
const cookieParser = require("cookie-parser");
const app = express();
const connectToDb = require("./db/db");
connectToDb();
app.use(cors());
app.use(express.json());
app.use(cookieParser());
app.use(express.urlencoded({ extended: true }));
app.use("/users", userRoutes);
module.exports = app;
